from python:3

run git clone https://github.com/MarianoSaez/Ahorcado-COMPU_2020.git

run pip3 install parameterized &&\
    pip3 install coverage

workdir /Ahorcado-COMPU_2020

cmd python3 -m unittest -b &&\
    python3 main.py
