FROM python:3

RUN git clone https://github.com/MatiasTomasRobbio/ComputacionMatiasRobbio.git
RUN pip3 install parameterized

WORKDIR /ComputacionMatiasRobbio/Insertion_Sorting

CMD ["python3", "-m", "unittest"]

